---
title: "Exercise 1: Dragon Management"
format: html
---

## Set environment and load packages

```{r setup, include=TRUE}

knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = TRUE
)

theme_set(theme_light())
```

```{r}

library(tidyverse)
library(janitor)
library(purrr)
```

## Exercise 1 - Dragon Management

#### Read data from NTNU wiki math:

```{r}

dragon_eggs <- read_csv("https://www.math.ntnu.no/emner/ST2304/2024v/Module03/DragonEggData.csv")
```

#### Clean data

```{r}

dragon_eggs_cleaned <- dragon_eggs |> 
  rename(
    sex = x,
    egg_number = ...1
  ) |> 
  mutate(
    sex = as_factor(
      case_when(
        sex == 0 ~ "Male",
        sex == 1 ~ "Female"
      )
    ),
    egg_number = as.integer(egg_number)
  )
```

### A1.

#### Plot absolute egg distribution and calculate female proportion

```{r}

# Absolute egg distribution

dragon_eggs_cleaned |>
  ggplot(
    aes(
      x = sex
    )
  ) +
  geom_histogram(
    stat = "count",
  )

# Female proportion

dragon_eggs_cleaned |> 
  filter(
    sex == "Female"
  ) |> 
  summarise(
   female_egg_prop = n() / 100
  )
```

The female proportion of eggs is 0.34.

### A3i-ii.

```{r}

# Calculate likelihoods for 1e4 possible values of p and plot the likelihood curve

fem_eggs <- 34
num_trials <- 100
probabilities <- seq(0.1, 0.9, length.out = 1e4)

likelihoods <- tibble(
  likelihood = dbinom(x = fem_eggs, size = num_trials, prob = probabilities),
  probabilities
)

likelihoods |> 
  ggplot(
    aes(
      x = probabilities,
      y = likelihood
    )
  ) +
  geom_point()
```

### A4.

```{r}

f = dbinom(
  x = 34,
  size = 1e3,
  prob = probabilities
)

optimise(f=dbinom, lower=0, upper=1, x=34, size=1e3, maximum=TRUE)
```

